/**
 * Seed data — manually curated vendors for initial demo + fallback when Google Places key is missing.
 * Run: npx tsx scripts/seed-vendors.ts
 */

import { VendorInsert } from './types'

export const SEED_VENDORS: VendorInsert[] = [
  // ── Goa Photographers ──────────────────────────────────────────────────
  {
    city: 'Goa', country_code: 'IN', category: 'photographer',
    name: 'Joseph Radhik',
    description: 'Internationally acclaimed wedding photographer known for candid storytelling. Extensive NRI and luxury destination wedding portfolio across Goa, Mumbai, and beyond.',
    website: 'https://josephradhik.com',
    instagram_handle: 'josephradhik',
    price_range_min: 5000, price_range_max: 20000, currency: 'USD',
    rating: 4.9, review_count: 120,
    specialties: ['candid', 'luxury', 'destination', 'NRI weddings'],
    languages: ['English', 'Hindi', 'Malayalam'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Goa', country_code: 'IN', category: 'photographer',
    name: 'Karthik Srinivasan Photography',
    description: 'Goa-based photographer specialising in beach and resort weddings. Known for vibrant natural-light work and seamless multilingual communication with international families.',
    website: 'https://karthiksrinivasan.com',
    instagram_handle: 'karthikweddings',
    price_range_min: 2000, price_range_max: 6000, currency: 'USD',
    rating: 4.7, review_count: 84,
    specialties: ['beach weddings', 'natural light', 'destination'],
    languages: ['English', 'Hindi', 'Tamil'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Goa DJs ────────────────────────────────────────────────────────────
  {
    city: 'Goa', country_code: 'IN', category: 'dj',
    name: 'DJ Rishi Sharma',
    description: 'Bollywood and crossover DJ with 12 years of destination wedding experience in Goa. Blends Bollywood, Punjabi, and EDM sets tailored to NRI crowds.',
    website: 'https://djrishisharma.com',
    instagram_handle: 'djrishigoa',
    price_range_min: 800, price_range_max: 2500, currency: 'USD',
    rating: 4.8, review_count: 63,
    specialties: ['Bollywood', 'Punjabi', 'EDM fusion', 'sangeet'],
    languages: ['English', 'Hindi', 'Punjabi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Goa Mehendi ────────────────────────────────────────────────────────
  {
    city: 'Goa', country_code: 'IN', category: 'mehendi_artist',
    name: 'Meena Mehendi Studio',
    description: 'Full-team mehendi studio covering bride, bridesmaids, and family. Specialises in intricate Rajasthani and Arabic fusion designs for beach and resort settings.',
    website: null,
    instagram_handle: 'meenamehendi_goa',
    price_range_min: 300, price_range_max: 1200, currency: 'USD',
    rating: 4.6, review_count: 41,
    specialties: ['Rajasthani', 'Arabic fusion', 'bridal party'],
    languages: ['English', 'Hindi', 'Konkani'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Bali Photographers ─────────────────────────────────────────────────
  {
    city: 'Bali', country_code: 'ID', category: 'photographer',
    name: 'Bali Indian Weddings Photography',
    description: 'Bali\'s leading Indian wedding photography studio with over 200 Indian ceremonies documented. Works with international families and coordinates with local vendors seamlessly.',
    website: 'https://baliindianweddings.com',
    instagram_handle: 'baliindianweddings',
    price_range_min: 3000, price_range_max: 9000, currency: 'USD',
    rating: 4.8, review_count: 97,
    specialties: ['Indian ceremonies in Bali', 'temple weddings', 'NRI weddings'],
    languages: ['English', 'Hindi', 'Balinese'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Bali', country_code: 'ID', category: 'decorator_florist',
    name: 'Tirtha Uluwatu Floral',
    description: 'Luxury floral and mandap decoration specialists at Tirtha Uluwatu and other cliff-top Bali venues. Experienced with Indian wedding aesthetic — marigold, lotus, and jasmine arrangements.',
    website: 'https://tirthaevents.com',
    instagram_handle: 'tirthaevents',
    price_range_min: 4000, price_range_max: 20000, currency: 'USD',
    rating: 4.9, review_count: 55,
    specialties: ['mandap decoration', 'marigold setups', 'cliff-top venues', 'luxury'],
    languages: ['English', 'Balinese', 'Indonesian'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Bangkok ────────────────────────────────────────────────────────────
  {
    city: 'Bangkok', country_code: 'TH', category: 'photographer',
    name: 'The Glow Story — Bangkok',
    description: 'Award-winning South Asian wedding photographer based in Bangkok. Portfolio spans Thai luxury resort venues with full Indian ceremony coverage including baraat and pheras.',
    website: 'https://theglowstory.com',
    instagram_handle: 'theglowstory',
    price_range_min: 3500, price_range_max: 10000, currency: 'USD',
    rating: 4.9, review_count: 72,
    specialties: ['South Asian weddings', 'luxury resorts', 'pheras', 'baraat'],
    languages: ['English', 'Hindi', 'Thai'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Bangkok', country_code: 'TH', category: 'wedding_planner',
    name: 'Bangkok Indian Wedding Planners',
    description: 'Full-service Indian wedding planning in Bangkok with in-house priest coordination, mandap import, and vendor network across all ceremony categories.',
    website: null,
    instagram_handle: 'bangkokindianwedding',
    price_range_min: 5000, price_range_max: 25000, currency: 'USD',
    rating: 4.7, review_count: 38,
    specialties: ['full-service planning', 'priest coordination', 'mandap', 'multi-day events'],
    languages: ['English', 'Hindi', 'Thai'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Udaipur ────────────────────────────────────────────────────────────
  {
    city: 'Udaipur', country_code: 'IN', category: 'photographer',
    name: 'WeddingSutra Films — Udaipur',
    description: 'Palace and lake-view wedding specialists in Udaipur. Cinematic storytelling with heritage venue expertise — City Palace, Taj Lake Palace, Devi Garh.',
    website: 'https://weddingsutra.com',
    instagram_handle: 'weddingsutrafilms',
    price_range_min: 4000, price_range_max: 15000, currency: 'USD',
    rating: 4.8, review_count: 88,
    specialties: ['palace weddings', 'lake view', 'heritage venues', 'cinematic'],
    languages: ['English', 'Hindi', 'Rajasthani'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Udaipur', country_code: 'IN', category: 'mehendi_artist',
    name: 'Rajasthani Mehendi Masters',
    description: 'Third-generation mehendi artists specialising in traditional Rajasthani bridal mehendi for palace weddings. Team of 8 artists for large wedding parties.',
    website: null,
    instagram_handle: 'rajasthanimehendi',
    price_range_min: 250, price_range_max: 800, currency: 'USD',
    rating: 4.7, review_count: 156,
    specialties: ['traditional Rajasthani', 'bridal', 'large party coverage'],
    languages: ['Hindi', 'Rajasthani', 'English'],
    has_nri_experience: false,
    source: 'manual_curated',
  },

  // ── Dubai ──────────────────────────────────────────────────────────────
  {
    city: 'Dubai', country_code: 'AE', category: 'wedding_planner',
    name: 'Shaadi by Ritu — Dubai',
    description: 'Dubai\'s top Indian wedding planning firm with 15 years in the UAE. End-to-end logistics for multi-day weddings at Atlantis, Burj Al Arab, and desert venues.',
    website: 'https://shaadibyritu.com',
    instagram_handle: 'shaadibyritu',
    price_range_min: 15000, price_range_max: 80000, currency: 'USD',
    rating: 4.9, review_count: 203,
    specialties: ['luxury', 'multi-day events', 'desert weddings', 'Atlantis', 'Burj Al Arab'],
    languages: ['English', 'Hindi', 'Arabic', 'Gujarati'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Dubai', country_code: 'AE', category: 'dj',
    name: 'DJ Sukh — Dubai',
    description: 'Dubai-based Bollywood and Bhangra DJ with experience at JW Marriott, Atlantis, and private desert events. Known for reading multilingual crowds.',
    website: null,
    instagram_handle: 'djsukhdubai',
    price_range_min: 1200, price_range_max: 5000, currency: 'USD',
    rating: 4.8, review_count: 44,
    specialties: ['Bollywood', 'Bhangra', 'desert events', 'luxury venues'],
    languages: ['English', 'Hindi', 'Punjabi', 'Arabic'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Jaipur ─────────────────────────────────────────────────────────────
  {
    city: 'Jaipur', country_code: 'IN', category: 'photographer',
    name: 'Morvi Images',
    description: 'Jaipur\'s most sought-after wedding photography studio, known for palace and haveli settings. Extensive NRI portfolio at Samode Palace, Rambagh, and Jai Mahal — candid storytelling meets Rajasthani grandeur.',
    website: 'https://morviimages.com',
    instagram_handle: 'morviimages',
    price_range_min: 3500, price_range_max: 12000, currency: 'USD',
    rating: 4.9, review_count: 174,
    specialties: ['palace weddings', 'candid', 'heritage venues', 'NRI weddings'],
    languages: ['English', 'Hindi', 'Rajasthani'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Jaipur', country_code: 'IN', category: 'decorator_florist',
    name: 'Ferns N Petals Events — Jaipur',
    description: 'Full-scale floral and decor house specialising in royal Rajasthani wedding aesthetics. Marigold mandaps, rose-draped baraat entries, and fort-courtyard lighting installations.',
    website: 'https://fnp.in',
    instagram_handle: 'fnpevents',
    price_range_min: 5000, price_range_max: 40000, currency: 'USD',
    rating: 4.6, review_count: 89,
    specialties: ['marigold decor', 'mandap', 'royal Rajasthani', 'fort weddings'],
    languages: ['English', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Jaipur', country_code: 'IN', category: 'wedding_planner',
    name: 'Rani Pink Events',
    description: 'Boutique Jaipur wedding planning firm with deep access to palace and heritage venue networks. Specialises in coordinating 3–5 day NRI celebrations across multiple Rajasthan cities.',
    website: null,
    instagram_handle: 'ranipinkevents',
    price_range_min: 8000, price_range_max: 50000, currency: 'USD',
    rating: 4.8, review_count: 62,
    specialties: ['palace venue access', 'multi-city Rajasthan', 'NRI weddings', 'multi-day events'],
    languages: ['English', 'Hindi', 'Rajasthani'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Jodhpur ────────────────────────────────────────────────────────────
  {
    city: 'Jodhpur', country_code: 'IN', category: 'photographer',
    name: 'Devika Narain & Co.',
    description: 'Celebrity wedding photographer and director with a strong Jodhpur palace portfolio — Umaid Bhawan, Mehrangarh Fort, Bal Samand. Documentary style with a cinematic editorial edge.',
    website: 'https://devikanarain.com',
    instagram_handle: 'devikanarain',
    price_range_min: 8000, price_range_max: 30000, currency: 'USD',
    rating: 5.0, review_count: 58,
    specialties: ['Umaid Bhawan', 'Mehrangarh Fort', 'editorial', 'celebrity weddings'],
    languages: ['English', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Jodhpur', country_code: 'IN', category: 'wedding_planner',
    name: 'Weddings by Neeraj Kamra',
    description: 'One of India\'s top luxury wedding planners based in Jodhpur with unmatched access to Umaid Bhawan Palace and Mehrangarh Fort. End-to-end production for 300–2000 guest celebrations.',
    website: 'https://neerajkamra.com',
    instagram_handle: 'neerajkamra',
    price_range_min: 20000, price_range_max: 200000, currency: 'USD',
    rating: 4.9, review_count: 112,
    specialties: ['Umaid Bhawan', 'ultra-luxury', 'large scale', 'palace production'],
    languages: ['English', 'Hindi', 'Rajasthani'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Jodhpur', country_code: 'IN', category: 'decorator_florist',
    name: 'Saarthak Entertainments — Jodhpur',
    description: 'Fort and palace décor specialists with in-house fabrication for large-scale Rajasthani-themed installations. Known for dramatic lighting rigs at Mehrangarh and Umaid Bhawan.',
    website: 'https://saarthak.in',
    instagram_handle: 'saarthakentertainments',
    price_range_min: 10000, price_range_max: 80000, currency: 'USD',
    rating: 4.7, review_count: 47,
    specialties: ['fort décor', 'lighting production', 'large-scale fabrication', 'palace weddings'],
    languages: ['English', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Jodhpur', country_code: 'IN', category: 'mehendi_artist',
    name: 'Sonu Mehendi Artist — Jodhpur',
    description: 'Rajasthan\'s celebrated mehendi master, trained in traditional Marwari bridal design. Travels across palace venues with a team of six for large bridal parties.',
    website: null,
    instagram_handle: 'sonumehendi_jodhpur',
    price_range_min: 400, price_range_max: 1500, currency: 'USD',
    rating: 4.8, review_count: 230,
    specialties: ['Marwari bridal', 'full-body design', 'large bridal party'],
    languages: ['Hindi', 'Rajasthani', 'English'],
    has_nri_experience: false,
    source: 'manual_curated',
  },

  // ── Rishikesh ──────────────────────────────────────────────────────────
  {
    city: 'Rishikesh', country_code: 'IN', category: 'wedding_planner',
    name: 'Ananda Weddings — Rishikesh',
    description: 'Boutique planner specialising in intimate luxury weddings at Rishikesh\'s spa retreats and riverside venues — Ananda in the Himalayas, Taj Rishikesh, and private forest clearings. Popular with NRI couples seeking a spiritual, nature-immersive celebration.',
    website: null,
    instagram_handle: 'anandaweddingsrishikesh',
    price_range_min: 10000, price_range_max: 60000, currency: 'USD',
    rating: 4.8, review_count: 34,
    specialties: ['intimate luxury', 'Himalayan venues', 'riverside', 'spiritual ceremonies'],
    languages: ['English', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Rishikesh', country_code: 'IN', category: 'photographer',
    name: 'The Wanderers — Rishikesh',
    description: 'Adventure and destination wedding photographers specialising in Rishikesh\'s dramatic Himalayan backdrops. Drone reels of forest pheras, Ganga aarti ceremonies, and white-water adjacent celebrations.',
    website: 'https://thewanderers.in',
    instagram_handle: 'thewanderers_weddings',
    price_range_min: 2500, price_range_max: 7000, currency: 'USD',
    rating: 4.7, review_count: 51,
    specialties: ['Himalayan destinations', 'drone cinematography', 'outdoor ceremonies', 'candid'],
    languages: ['English', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Rishikesh', country_code: 'IN', category: 'decorator_florist',
    name: 'Jungle & Bloom — Rishikesh',
    description: 'Eco-conscious floral studio creating forest mandaps and riverbank ceremony setups using locally sourced wildflowers, marigolds, and bamboo. Natural aesthetic for Rishikesh\'s outdoor venues.',
    website: null,
    instagram_handle: 'jungleandbloom',
    price_range_min: 2000, price_range_max: 10000, currency: 'USD',
    rating: 4.6, review_count: 28,
    specialties: ['forest mandaps', 'eco decor', 'riverbank setups', 'wildflower arrangements'],
    languages: ['English', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },

  // ── Kerala ─────────────────────────────────────────────────────────────
  {
    city: 'Kerala', country_code: 'IN', category: 'wedding_planner',
    name: 'The Wedding Co. — Kerala',
    description: 'Kerala\'s leading destination wedding planner with a portfolio spanning backwater houseboat ceremonies, Malabar coast resorts, and plantation estates in Munnar. Experienced with NRI Hindu, Christian, and Muslim ceremonies.',
    website: 'https://theweddingco.in',
    instagram_handle: 'theweddingco_kerala',
    price_range_min: 8000, price_range_max: 60000, currency: 'USD',
    rating: 4.8, review_count: 77,
    specialties: ['backwater weddings', 'houseboat ceremonies', 'plantation estates', 'Munnar', 'multi-faith'],
    languages: ['English', 'Hindi', 'Malayalam'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Kerala', country_code: 'IN', category: 'photographer',
    name: 'Amour Affairs Photography — Kerala',
    description: 'Kerala-based photography duo renowned for backwater and coastal wedding shoots. Houseboat golden-hour sessions and lush plantation ceremonies are their signature — widely featured in Indian wedding publications.',
    website: 'https://amouraffairs.in',
    instagram_handle: 'amouraffairsphoto',
    price_range_min: 2000, price_range_max: 7000, currency: 'USD',
    rating: 4.9, review_count: 143,
    specialties: ['backwater shoots', 'houseboat sessions', 'coastal weddings', 'editorial'],
    languages: ['English', 'Hindi', 'Malayalam'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Kerala', country_code: 'IN', category: 'decorator_florist',
    name: 'Blooms & Backwaters — Alleppey',
    description: 'Tropical floral design studio working across Kerala\'s backwater resorts and Kochi venues. Signature style: banana leaf mandaps, jasmine garlands, and lotus floating arrangements.',
    website: null,
    instagram_handle: 'bloomsandbackwaters',
    price_range_min: 2500, price_range_max: 15000, currency: 'USD',
    rating: 4.7, review_count: 59,
    specialties: ['tropical floral', 'banana leaf mandap', 'jasmine arrangements', 'Alleppey backwaters'],
    languages: ['English', 'Malayalam', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
  {
    city: 'Kerala', country_code: 'IN', category: 'mehendi_artist',
    name: 'Kerala Mehendi Studio — Kochi',
    description: 'Kochi-based mehendi team skilled in Arabic, Rajasthani, and Kerala-fusion designs. Travels to all major Kerala wedding venues including backwater resorts and Malabar heritage properties.',
    website: null,
    instagram_handle: 'keralamehendi',
    price_range_min: 200, price_range_max: 800, currency: 'USD',
    rating: 4.6, review_count: 88,
    specialties: ['Arabic fusion', 'Kerala-style', 'destination travel', 'bridal party'],
    languages: ['English', 'Malayalam', 'Hindi'],
    has_nri_experience: true,
    source: 'manual_curated',
  },
]
