'use client';

import {
  Box,
  Typography,
  Paper,
  IconButton,
  Switch,
  Chip,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Button,
  Stack,
  CircularProgress,
} from '@mui/material';
import { Delete, AutoAwesome } from '@mui/icons-material';
import { useState } from 'react';

const CATEGORIES = [
  { value: 'dining', label: 'Dining' },
  { value: 'activities', label: 'Activities' },
  { value: 'transportation', label: 'Transportation' },
  { value: 'accommodation', label: 'Accommodation' },
  { value: 'local_tips', label: 'Local Tips' },
  { value: 'weather', label: 'Weather' },
  { value: 'emergency', label: 'Emergency' },
  { value: 'nightlife', label: 'Nightlife' },
  { value: 'shopping', label: 'Shopping' },
  { value: 'cultural_etiquette', label: 'Cultural & Etiquette' },
  { value: 'other', label: 'Other' },
];

const CATEGORY_COLORS: Record<string, string> = {
  dining: '#FF6B35',
  activities: '#4CAF50',
  transportation: '#2196F3',
  accommodation: '#9C27B0',
  local_tips: '#FF9800',
  weather: '#0288D1',
  emergency: '#D32F2F',
  nightlife: '#7B1FA2',
  shopping: '#E91E63',
  cultural_etiquette: '#795548',
  other: '#607D8B',
};

interface KnowledgeEntry {
  id: string;
  title: string;
  content: string;
  category: string;
  is_active: boolean;
  order_index: number;
  source?: string;
}

interface ConciergeKnowledgeEntryProps {
  entry: KnowledgeEntry;
  onUpdate: (id: string, data: Partial<KnowledgeEntry>) => void | Promise<void>;
  onDelete: (id: string) => void | Promise<void>;
  isViewOnly?: boolean;
}

export default function ConciergeKnowledgeEntry({ entry, onUpdate, onDelete, isViewOnly }: ConciergeKnowledgeEntryProps) {
  const [editing, setEditing] = useState(false);
  const [editTitle, setEditTitle] = useState(entry.title);
  const [editContent, setEditContent] = useState(entry.content);
  const [editCategory, setEditCategory] = useState(entry.category);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);

  const handleSave = async () => {
    setSaving(true);
    try {
      await onUpdate(entry.id, {
        title: editTitle,
        content: editContent,
        category: editCategory,
      });
      setEditing(false);
    } finally {
      setSaving(false);
    }
  };

  const handleCancel = () => {
    setEditTitle(entry.title);
    setEditContent(entry.content);
    setEditCategory(entry.category);
    setEditing(false);
  };

  const categoryLabel = CATEGORIES.find(c => c.value === entry.category)?.label || entry.category;
  const categoryColor = CATEGORY_COLORS[entry.category] || CATEGORY_COLORS.other;
  const isAutoGenerated = entry.source === 'auto_generated';

  if (editing) {
    return (
      <Paper
        elevation={0}
        sx={{
          p: 2.5,
          borderRadius: 1,
          border: '1px solid rgba(0,0,0,0.15)',
          bgcolor: 'white',
        }}
      >
        <Stack spacing={2}>
          <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
            <TextField
              label="Title"
              value={editTitle}
              onChange={(e) => setEditTitle(e.target.value)}
              size="small"
              fullWidth
              sx={{
                '& .MuiOutlinedInput-root': { bgcolor: 'white', borderRadius: '10px', height: 40, '& fieldset': { borderColor: 'rgba(0,0,0,0.23)' }, '&:hover fieldset': { borderColor: 'rgba(0,0,0,0.4)' }, '&.Mui-focused fieldset': { borderColor: '#DE3F5E' } },
                '& .MuiInputLabel-root': { color: '#4a4a4a', fontWeight: 500, '&.Mui-focused': { color: '#DE3F5E' } },
              }}
            />
            <FormControl size="small" sx={{ minWidth: 160, flexShrink: 0, '& .MuiOutlinedInput-root': { height: 40 } }}>
              <InputLabel sx={{ color: '#4a4a4a', fontWeight: 500, '&.Mui-focused': { color: '#DE3F5E' } }}>Category</InputLabel>
              <Select
                value={editCategory}
                label="Category"
                onChange={(e) => setEditCategory(e.target.value)}
                sx={{ bgcolor: 'white', borderRadius: '10px', color: '#1a1a1a', '& fieldset': { borderColor: 'rgba(0,0,0,0.23)' }, '&:hover fieldset': { borderColor: 'rgba(0,0,0,0.4)' }, '&.Mui-focused fieldset': { borderColor: '#DE3F5E' } }}
              >
                {CATEGORIES.map((cat) => (
                  <MenuItem key={cat.value} value={cat.value}>{cat.label}</MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
          <TextField
            label="Content"
            value={editContent}
            onChange={(e) => setEditContent(e.target.value)}
            size="small"
            fullWidth
            multiline
            minRows={3}
            sx={{
              '& .MuiOutlinedInput-root': { bgcolor: 'white', borderRadius: '10px', '& fieldset': { borderColor: 'rgba(0,0,0,0.23)' }, '&:hover fieldset': { borderColor: 'rgba(0,0,0,0.4)' }, '&.Mui-focused fieldset': { borderColor: '#DE3F5E' } },
              '& .MuiInputLabel-root': { color: '#4a4a4a', fontWeight: 500, '&.Mui-focused': { color: '#DE3F5E' } },
            }}
          />
          <Box sx={{ display: 'flex', gap: 1, justifyContent: 'flex-end' }}>
            <Button
              size="small"
              onClick={handleCancel}
              sx={{ textTransform: 'none', color: '#6a6a6a', borderRadius: '10px' }}
            >
              Cancel
            </Button>
            <Button
              size="small"
              variant="contained"
              onClick={handleSave}
              disabled={!editTitle.trim() || !editContent.trim() || saving}
              sx={{
                textTransform: 'none',
                bgcolor: '#DE3F5E',
                borderRadius: '10px',
                '&:hover': { bgcolor: '#c73552' },
              }}
            >
              {saving ? <CircularProgress size={18} color="inherit" /> : 'Save'}
            </Button>
          </Box>
        </Stack>
      </Paper>
    );
  }

  return (
    <Paper
      elevation={0}
      sx={{
        p: 2.5,
        borderRadius: 1,
        border: '1px solid rgba(0,0,0,0.07)',
        bgcolor: entry.is_active ? 'white' : '#FAFAFA',
        opacity: entry.is_active ? 1 : 0.65,
        transition: 'opacity 0.2s',
        cursor: !isViewOnly ? 'pointer' : 'default',
        '&:hover': !isViewOnly ? { borderColor: '#ddd' } : {},
      }}
      onClick={() => !isViewOnly && setEditing(true)}
    >
      <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2, cursor: !isViewOnly ? 'pointer' : 'default' }}>
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.75, flexWrap: 'wrap' }}>
            <Typography sx={{ fontWeight: 600, fontSize: '0.9rem', color: '#1a1a1a' }}>
              {entry.title}
            </Typography>
            <Chip
              label={categoryLabel}
              size="small"
              sx={{
                fontSize: '0.65rem',
                height: 20,
                bgcolor: `${categoryColor}15`,
                color: categoryColor,
                fontWeight: 600,
              }}
            />
            {isAutoGenerated && (
              <Chip
                icon={<AutoAwesome sx={{ fontSize: '12px !important' }} />}
                label="AI Generated"
                size="small"
                sx={{
                  fontSize: '0.6rem',
                  height: 20,
                  bgcolor: '#DE3F5E10',
                  color: '#DE3F5E',
                  fontWeight: 600,
                  '& .MuiChip-icon': { color: '#DE3F5E', ml: '4px' },
                }}
              />
            )}
          </Box>
          <Typography
            variant="body2"
            sx={{
              color: '#4a4a4a',
              lineHeight: 1.6,
              whiteSpace: 'pre-wrap',
              fontSize: '0.85rem',
            }}
          >
            {entry.content.length > 200 ? entry.content.slice(0, 200) + '...' : entry.content}
          </Typography>
        </Box>
        {!isViewOnly && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, flexShrink: 0 }} onClick={(e) => e.stopPropagation()}>
            <Switch
              size="small"
              checked={entry.is_active}
              onChange={(e) => onUpdate(entry.id, { is_active: e.target.checked })}
              sx={{
                '& .MuiSwitch-switchBase': { color: '#999' },
                '& .MuiSwitch-track': { bgcolor: '#bbb' },
                '& .MuiSwitch-switchBase.Mui-checked': { color: '#DE3F5E' },
                '& .Mui-checked + .MuiSwitch-track': { bgcolor: '#DE3F5E' },
              }}
            />
            <IconButton
              size="small"
              disabled={deleting}
              onClick={async (e) => {
                e.stopPropagation();
                setDeleting(true);
                try { await onDelete(entry.id); } finally { setDeleting(false); }
              }}
            >
              {deleting ? <CircularProgress size={18} sx={{ color: '#6a6a6a' }} /> : <Delete sx={{ fontSize: 18, color: '#6a6a6a' }} />}
            </IconButton>
          </Box>
        )}
      </Box>
    </Paper>
  );
}
