import { CarouselSlide } from '@/lib/supabase/wedding-service';

export interface EventTemplate {
  name: string;
  slug: string;
  dress_code: string;
  dress_code_icon: string;
  dress_code_description: string;
  outfit_ideas_women: string[];
  outfit_ideas_men: string[];
  ritual_name: string;
  ritual_description: string;
  gradient_background: string;
  date: string;
  time: string;
  carousel_slides?: CarouselSlide[];
}

export const EVENT_TEMPLATES: EventTemplate[] = [
  {
    name: 'Welcome Lunch',
    slug: 'welcome-lunch',
    dress_code: 'Casual Elegant',
    dress_code_icon: 'flower',
    dress_code_description: 'Smart casual attire - comfortable yet stylish for a relaxed welcome gathering.',
    outfit_ideas_women: [
      'Casual Anarkali or light Salwar Kameez',
      'Flowy maxi dress or sundress',
      'Kurti with jeans or palazzo pants',
      'Casual saree in light fabric',
      'Cotton or linen suit',
    ],
    outfit_ideas_men: [
      'Casual Kurta with jeans',
      'Linen shirt with chinos',
      'Polo shirt with dress pants',
      'Light-colored casual button-down',
      'Nehru jacket (optional) with casual pants',
    ],
    ritual_name: 'Welcome Gathering',
    ritual_description: 'A relaxed lunch to welcome guests and kick off the wedding celebrations. Perfect for meeting family and friends in a casual setting.',
    gradient_background: '/images/backgrounds/pearl.webp',
    date: '',
    time: '12:00 PM',
  },
  {
    name: 'Haldi',
    slug: 'haldi',
    dress_code: 'Shades of Yellow',
    dress_code_icon: 'sunflower',
    dress_code_description: 'Bright, festive yellows! Think sunshine and turmeric.',
    outfit_ideas_women: [
      'Yellow Anarkali or Salwar Kameez',
      'Lehenga in yellow/gold tones',
      'Yellow Saree with contrasting blouse',
      'Kurti with palazzo pants',
      'Floral yellow print dress',
    ],
    outfit_ideas_men: [
      'Yellow Kurta with white pajama',
      'Yellow Nehru jacket',
      'Casual yellow shirt with chinos',
      'Yellow sherwani (if going formal)',
      'Colored dhoti with kurta',
    ],
    ritual_name: 'The Haldi Ceremony',
    ritual_description: 'A turmeric paste is applied to the bride and groom for blessings and radiant skin. Prepare to get messy and have fun!',
    gradient_background: '/images/backgrounds/GradientYellow.webp',
    date: '',
    time: '2:00 PM',
    carousel_slides: [
      {
        type: 'three_lines',
        top_label: 'THE CEREMONY',
        main_heading: 'Haldi',
        body_text: 'A turmeric paste is applied to the bride and groom for blessings and radiant skin. Prepare to get messy and have fun!',
      },
      {
        type: 'two_sections',
        section1_header: 'WOMEN',
        section1_items: ['Yellow Anarkali', 'Lehenga in gold tones', 'Yellow Saree', 'Kurti with palazzo'],
        section2_header: 'MEN',
        section2_items: ['Yellow Kurta with white pajama', 'Yellow Nehru jacket', 'Casual yellow shirt'],
      },
    ],
  },
  {
    name: 'Baraat',
    slug: 'baraat',
    dress_code: 'Festive & Bold',
    dress_code_icon: 'trumpet',
    dress_code_description: 'Vibrant colors and festive wear for the groom\'s procession! Think celebration mode.',
    outfit_ideas_women: [
      'Colorful Lehenga Choli',
      'Embellished Anarkali',
      'Designer Saree with heavy blouse',
      'Sharara or Gharara set',
      'Indo-western fusion gown',
    ],
    outfit_ideas_men: [
      'Sherwani with churidar',
      'Bandhgala suit',
      'Embroidered Kurta with dhoti',
      'Nehru jacket with trousers',
      'Traditional Jodhpuri suit',
    ],
    ritual_name: 'The Baraat',
    ritual_description: 'The groom arrives on horseback (or in style!) with his family and friends dancing to dhol beats. A spectacular, energetic entrance!',
    gradient_background: '/images/backgrounds/GradientJaggo.webp',
    date: '',
    time: '4:00 PM',
  },
  {
    name: 'Varmala',
    slug: 'varmala',
    dress_code: 'Traditional Elegance',
    dress_code_icon: 'bouquet',
    dress_code_description: 'Elegant traditional wear for the sacred garland exchange ceremony.',
    outfit_ideas_women: [
      'Traditional Lehenga or Saree',
      'Elegant Salwar Kameez',
      'Pastel Anarkali',
      'Designer Sharara',
      'Soft-colored traditional outfit',
    ],
    outfit_ideas_men: [
      'Traditional Sherwani',
      'Kurta Pajama with jacket',
      'Bandhgala in elegant colors',
      'Achkan with churidar',
      'Indo-western formal attire',
    ],
    ritual_name: 'The Varmala',
    ritual_description: 'The bride and groom exchange flower garlands, symbolizing their acceptance of each other as life partners. A beautiful and meaningful moment!',
    gradient_background: '/images/backgrounds/pearl.webp',
    date: '',
    time: '5:00 PM',
  },
  {
    name: 'Jaggo',
    slug: 'jaggo',
    dress_code: 'Vibrant & Festive',
    dress_code_icon: 'party-popper',
    dress_code_description: 'Bold colors, sequins, and celebration mode! The night before the wedding calls for your most festive attire.',
    outfit_ideas_women: [
      'Colorful Lehenga Choli',
      'Embellished Anarkali',
      'Sharara or Gharara set',
      'Designer Saree with heavy blouse',
      'Indo-western fusion gown',
    ],
    outfit_ideas_men: [
      'Sherwani with churidar',
      'Bandhgala suit',
      'Embroidered Kurta with dhoti',
      'Nehru jacket with trousers',
      'Traditional Jodhpuri suit',
    ],
    ritual_name: 'The Jaggo',
    ritual_description: 'An energetic night celebration before the wedding day! Family and friends sing, dance, and parade through the streets with decorated pots and lights.',
    gradient_background: '/images/backgrounds/GradientJaggo.webp',
    date: '',
    time: '8:00 PM',
  },
  {
    name: 'Anand Karaj',
    slug: 'anand-karaj',
    dress_code: 'Traditional Elegance',
    dress_code_icon: 'lotus',
    dress_code_description: 'Elegant pastels and traditional wear for the sacred ceremony.',
    outfit_ideas_women: [
      'Pastel Lehenga or Saree',
      'Traditional Salwar Kameez',
      'Light-colored Anarkali',
      'Elegant Sharara',
      'Soft pink or peach outfits',
    ],
    outfit_ideas_men: [
      'Traditional Kurta Pajama',
      'Light-colored Sherwani',
      'Nehru jacket in pastels',
      'Bandhgala in cream/beige',
      'Traditional Achkan',
    ],
    ritual_name: 'The Anand Karaj',
    ritual_description: 'The Sikh wedding ceremony where the couple circles the Guru Granth Sahib four times, symbolizing their union.',
    gradient_background: '/images/backgrounds/pearl.webp',
    date: '',
    time: '10:00 AM',
  },
  {
    name: 'Sangeet',
    slug: 'sangeet',
    dress_code: 'Glamorous & Festive',
    dress_code_icon: 'microphone',
    dress_code_description: 'Dress to impress! Glamorous, festive attire for an evening of music and dance performances.',
    outfit_ideas_women: [
      'Designer Lehenga or Saree',
      'Embellished Anarkali',
      'Sequined or velvet outfit',
      'Indo-western fusion gown',
      'Statement jewelry encouraged',
    ],
    outfit_ideas_men: [
      'Formal Sherwani',
      'Designer Kurta with jacket',
      'Velvet or silk Bandhgala',
      'Three-piece suit',
      'Indo-western blazer with churidar',
    ],
    ritual_name: 'Sangeet Night',
    ritual_description: 'An evening of music, dance performances by family and friends, and celebration! Be prepared to sing, dance, and enjoy the show.',
    gradient_background: '/images/backgrounds/GradientReception.webp',
    date: '',
    time: '6:00 PM',
    carousel_slides: [
      {
        type: 'three_lines',
        top_label: 'THE CELEBRATION',
        main_heading: 'Sangeet Night',
        body_text: 'An evening of music, dance performances by family and friends, and celebration! Be prepared to sing, dance, and enjoy the show.',
      },
      {
        type: 'two_sections',
        section1_header: 'WOMEN',
        section1_items: ['Designer Lehenga or Saree', 'Embellished Anarkali', 'Sequined or velvet outfit', 'Indo-western fusion gown'],
        section2_header: 'MEN',
        section2_items: ['Formal Sherwani', 'Designer Kurta with jacket', 'Velvet or silk Bandhgala', 'Three-piece suit'],
      },
    ],
  },
  {
    name: 'Reception',
    slug: 'reception',
    dress_code: 'Cocktail Glam',
    dress_code_icon: 'sparkles',
    dress_code_description: 'Dress to impress! Formal cocktail attire with glamorous touches.',
    outfit_ideas_women: [
      'Evening gown or cocktail dress',
      'Glamorous Saree with embellished blouse',
      'Designer Lehenga',
      'Sequined or velvet outfit',
      'Indo-western fusion gown',
    ],
    outfit_ideas_men: [
      'Black tie or Tuxedo',
      'Formal Sherwani',
      'Three-piece suit',
      'Designer Kurta with jacket',
      'Velvet or silk Bandhgala',
    ],
    ritual_name: 'Wedding Reception',
    ritual_description: 'An elegant evening of dinner, toasts, and celebration of the newlyweds! Time to party in style.',
    gradient_background: '/images/backgrounds/GradientReception.webp',
    date: '',
    time: '7:00 PM',
    carousel_slides: [
      {
        type: 'three_lines',
        top_label: 'THE CELEBRATION',
        main_heading: 'Sangeet & Reception',
        body_text: 'Evening kicks off with a high-energy Sangeet of choreographed dances, then flows into a formal Reception of dinner, toasts, and first dances—a perfect blend of party and polish.',
      },
      {
        type: 'two_sections',
        section1_header: 'WOMEN',
        section1_items: ['Evening Gowns', 'Embellished Sarees', 'Fusion Co-Ord Sets', 'Cocktail Lehengas'],
        section2_header: 'MEN',
        section2_items: ['Tuxedos & Dinner Suits', 'Tailored Sherwanis', 'Patterned Nehru Jackets'],
      },
    ],
  },
  {
    name: 'Pool Party',
    slug: 'pool-party',
    dress_code: 'Beach Chic',
    dress_code_icon: 'beach',
    dress_code_description: 'Beachwear, swimsuits, and resort casual. Bring your summer vibes!',
    outfit_ideas_women: [
      'Swimsuit with cover-up',
      'Maxi dress or beach dress',
      'Kaftan or resort wear',
      'Shorts with crop top',
      'Flowy palazzo with tank',
    ],
    outfit_ideas_men: [
      'Swim shorts',
      'Linen shirt (unbuttoned or casual)',
      'Beach shorts with tee',
      'Resort casual attire',
      'Hawaiian shirt',
    ],
    ritual_name: 'Pool Party Celebration',
    ritual_description: 'Relax, swim, and celebrate by the pool with music, drinks, and good vibes!',
    gradient_background: '/images/backgrounds/GradientPoolParty.webp',
    date: '',
    time: '2:00 PM',
  },
];
